Documentation
ut-robotics/picr22-team-twelve pull request #8
Opened 2022-10-16 08:55 UTC by T2heke

2023-01-08 15:49 UTC, T2heke commented
My part of the documentation is ready for review.

2023-01-08 16:53 UTC, ReikoR requested changes

2023-01-08 16:53 UTC, ReikoR commented on README.asciidoc
> +The `main.py` holds the state machine for the driving logic. For configurations check the software branch readme file. The overall logic of the code is as shown on this https://drive.google.com/file/
Add block diagram to the repository as a SVG image and add the image to the README.

2023-01-10 18:13 UTC, ReikoR requested changes

2023-01-10 18:13 UTC, ReikoR commented on README.asciidoc
> +image:robot_CAD.PNG[]
Hide joints in Fusion 360 and create a new image.

2023-01-10 18:13 UTC, ReikoR commented on README.asciidoc
> +I learned that it is not all that difficult to create something as I first thought. Since I had used other CAD programs before this course then I also learned a thing or two about Fusion 360 and comp
> Got to know how to do CAD

I'm guessing you mean "Got to know how to do CAM".

CAD -> CAM?

2023-01-10 18:35 UTC, ReikoR approved these changes

2023-01-11 19:58 UTC, merged